version: '3'
services:
  my-spring-boot-app:
    image: my-spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:8081"
    networks:
      - my-spring-boot-app-network
networks:
  my-spring-boot-app-network:
    driver: bridge
